#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
clear
echo -e "\E[44;1;37m    Instalar checkuser conecta4g     \E[0m" 
echo ""
echo -ne "\n\033[1;32mDe um enter para \033[1;37mcontinuar...\033[1;37m: "; read -r
clear
echo -e "\n\033[1;36mIniciando instalação \033[1;37mAGUARDE..."
apt-get install figlet -y > /dev/null 2>&1
pip3 install flask > /dev/null 2>&1
rm /bin/initcheck > /dev/null 2>&1
sleep 5
cd /bin || exit
wget https://raw.githubusercontent.com/Niltonjuniorxd/scriptssh/main/modulos/initcheck > /dev/null 2>&1
wget https://raw.githubusercontent.com/Niltonjuniorxd/scriptssh/main/modulos/userscheck > /dev/null 2>&1
chmod 777 initcheck > /dev/null 2>&1
chmod 777 userscheck > /dev/null 2>&1
clear
mkdir /etc/rec > /dev/null 2>&1
echo -e 'By: @KIRITO_SSH' > /etc/rec/licence
echo -e 'By: @KIRITO_SSH' > /usr/lib/licence
mkdir /usr/lib/checkuser > /dev/null 2>&1
cd /usr/lib/checkuser || exit
rm checkuser.py > /dev/null 2>&1
wget https://raw.githubusercontent.com/Niltonjuniorxd/scriptssh/main/modulos/checkuser.py > /dev/null 2>&1
chmod 777 checkuser.py > /dev/null 2>&1
clear
echo -e "        \033[1;37m • \033[1;32mInstalação concluída\033[1;37m • \033[0m"
sleep 2
clear
echo ""
echo -e "\033[1;31m \033[1;37mAtiver checkuser: \033[1;32m \033[0m"
echo ""
cat /dev/null > ~/.bash_history && history -c
exit